
Store GobalStore;
void Init();
void GarbageCollection();
void callback();
goods * WantGoodsById(int * res);
int LogginGoods();
int ChangeName(goods * g);
int ChangeCount(goods * g);
int ChangeGoods();
int RemoveById();
int RemoveByName();
int RemoveGoods();
int QueryGoods();
int SaleGoods();
int StockGoods();
int Loggin2S();
void PrintSumCount();
void PrintIdCount();
int StatisGoods();
int ListenMainKey();
